#!/bin/bash

### TO BE CONFIGURED MANUALLY ###
#MOBILEDET:
#PROJECT_NAME="mobiledet"
#S3_BUCKET="onnx-mobiledet-bucket"
#IMAGE_FILE="img_resized.npy"
#EXECUTION_TIMEOUT=30
#FUNCTION_MEMORY=256

#EFFICIENTDET:
PROJECT_NAME="efficientdet"
S3_BUCKET="onnx-efficientdet-bucket"
IMAGE_FILE="img_efficientdet.png"
EXECUTION_TIMEOUT=30
FUNCTION_MEMORY=1536

# NUMBER OF SLICES:
NUMBER_OF_SLICES=5

#################################

FUNCTION_NAME="${PROJECT_NAME}_${NUMBER_OF_SLICES}_slices"
LAMBDA_CODE="lambda_code/${PROJECT_NAME}"
INPUT_IMAGE_PATH="../../models/${PROJECT_NAME}/${IMAGE_FILE}"
PACKAGE_PATH="./packages/${PROJECT_NAME}"
ZIP_PACKAGE="${FUNCTION_NAME}.zip"
ZIP_PACKAGE_PATH="${PACKAGE_PATH}/${ZIP_PACKAGE}"
LAMBDA_HANDLER="${PROJECT_NAME}_lambda"
LAMBDA_HANDLER_PY="${LAMBDA_HANDLER}.py"


